name: release
on:
  workflow_dispatch:
    inputs:
      semver:
        description: The semver to use
        required: true
        default: patch
        type: choice
        options:
          - patch
          - minor
          - major
      otp_option:
        description: Should we use optic or alternate OTP option
        required: true
        type: choice
        options:
          - optic
          - alternate
  pull_request:
    types: [closed]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - uses: msgadi/optic-release-automation-action@feat/adding-alternate-flow
        with:
          npm-token: >-
            ${{ secrets[format('NPM_TOKEN_{0}', github.actor)] ||
            secrets.NPM_TOKEN }}
          optic-token: >-
            ${{ secrets[format('OPTIC_TOKEN_{0}', github.actor)] ||
            secrets.OPTIC_TOKEN }}
          semver: ${{ github.event.inputs.semver }}
          commit-message: 'chore: release {version}'
          build-command: npm ci
          provenance: true
